//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.GESTORPLUS.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("persona", Schema = "dbo")]
    
    public partial class persona
    {
        
        public persona()
        {
            this.usuario = new HashSet<usuario>();
        }
    
    	[Key()]	
    	public int id_persona { get; set; }
    	public string nombre { get; set; }
    	public string apellido_paterno { get; set; }
    	public string apellido_materno { get; set; }
    	public string email { get; set; }
    	public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    	public Nullable<bool> sexo { get; set; }
    
        
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
