//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.GESTORPLUS.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("usuario", Schema = "dbo")]
    
    public partial class usuario
    {
    	public int id_persona { get; set; }
    	public Nullable<int> id_institucion { get; set; }
    	[Key()]	
    	public int id_usuario { get; set; }
    
        public virtual institucion institucion { get; set; }
        public virtual persona persona { get; set; }
    }
}
